version: "3"
services:
  go-service:
    build:
      context: ./go-service
    ports:
      - "8081:8081"
  
  node-service:
    build: 
      context: ./node-service
    ports:
      - "8082:8082"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - go-service
      - node-service